### ISSUE TITLE
Quest Map Scout Data Collection

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/ESO_QuestMapScout#1]
The file you want to provide is `QuestMapScout.lua` from your `.\Documents\Elder Scrolls Online\live\SavedVariables` folder.

![image](https://user-images.githubusercontent.com/1912426/81147231-ba97ce80-8f2e-11ea-9486-93f495adae08.png)

**Comment by Gimplekin** [comment]
[QuestMapScout.zip](https://github.com/ESOUIMods/ESO_QuestMapScout/files/4591058/QuestMapScout.zip)

**Comment by Sharlikran** [comment]
@Gimplekin Ty very much

**Comment by MikeZeDev** [comment]
What zone do you miss? I can provide some french quest data.

**Comment by Sharlikran** [comment]
Je ne parle pas français, mais je vais essayer de traduire pour que je puisse répondre plus clairement.

1. Installez la nouvelle version de Quest Map Scout qui est 1.0.15
2. Supprimez le fichier QuestMapScout.lua de .\Documents\Elder Scrolls Online\live|SavedVariables
3. Veuillez contacter le site [Web d'ESOUI](https://www.esoui.com/downloads/info1022-QuestMap.html#comments) pour vous assurer que tout le monde a accès aux mêmes informations pour tous les bénévoles.

Qui collecte des données sur quelles cartes:

Hew's Bane: Gimplekin - Partial Information Received, Ty
Gold Coast: Gimplekin - Partial Information Received, Ty
Summerset: Sharlikran - In progress
Vvardenfel: Necropsi - Ongoing but almost collected
Northern Elsweyr: Sharlikran - Finished
Southern Elsweyr:
Murkmire:
Craglorn:
Clockwork City:

Player Test Server:

Western Skyrim:
Blackreach:

**Comment by MikeZeDev** [comment]
No need to translate, i am bilingual :D. Anyway, I think i already got Murkmire covered . I did a full quest run on a new character with the addon activated during MM event. Gonna play a bit more before uploading the file.

**Comment by Sharlikran** [comment]
@MikeZeDev were you questing with the latest version that requires LibGPS, I thi k 1.0.13 or higher?

**Comment by Sharlikran** [comment]
@MikeZeDev [QuestMapLog](https://github.com/ESOUIMods/ESO_QuestMapLog). I just remembered, I am using both Quest Map Scout and Quest Map Log as helpers to import data. Get the latest version of quest map log. Log on to all of your characters one by one, then log out of the game.

Go to your saved variables folder zip up the questmaplog.lua file and drag and drop it into here and I'll have all the names in French that you have available.

**Comment by MikeZeDev** [comment]
@Sharlikran I cant answer about libgps. Like i've said i collected Murkmire quests during Murkmire event.  I cant talk about the others, i may have a full CWC too. I launch Minion once a day to update my addons so it depends. They are always up to date , afaic.

When the server goes up, ill upload the saved variables you want.

**Comment by MikeZeDev** [comment]
[Quests.zip](https://github.com/ESOUIMods/ESO_QuestMapScout/files/4611223/Quests.zip)

**Comment by Sharlikran** [comment]
That's perfect thank you. :+1: 

You can delete the `QuestMapScout.lua` in your SavedVariables and once you have the new version I just uploaded a few minutes ago, you are good to go. Thank you so far.

**Comment by Necropsi** [comment]
New icons! I didn't rename them, so the name is the same as for the ! ones!

![Quest map](https://user-images.githubusercontent.com/65191164/81602816-8e1c0080-93cd-11ea-8c11-24444fdd0e63.png)

[icons.zip](https://github.com/ESOUIMods/ESO_QuestMapScout/files/4611625/icons.zip)

**Comment by Necropsi** [comment]
oh and should i also install Quest Map Log? or is Quest Map and Quest Map Scout enogh for what im doing?

**Comment by Sharlikran** [comment]
You can if you like. It will make sure I have names of quests.

However, if you have an English version of the game then Quest Map and Quest Map Scout are fine.

**Comment by Sharlikran** [comment]
@Necropsi I didn't need you to install Quest Map Log up until just now.

I finally found the oversight, flaw (bug basically) in my routines for updating the quest information. So some of the information will be inaccurate. :facepalm: 

So please install Quest Map Log, log onto all your chars and when you submit your `QuestMapScout.lua` for Vvardenfell turn in your `QuestMapLog.lua` at the same time.

**Comment by Necropsi** [comment]
ok, i have it installed! will log into chars now, and in afternoon continue to quest vvardenfell. i am so sorry it is taking so long but i had shitload of stuff to do in a last few days. will have more free time in the coming days!!

**Comment by Sharlikran** [comment]
Real life is more important. Take your time. I have a lot to work on anyway.

**Comment by Sharlikran** [comment]
@MikeZeDev I was able to update both German and French quest names. Now I have to build a table of the names with the ID and it's complete.

https://github.com/ESOUIMods/ESO_QuestMap/commit/f02501db7a033169eb52d7bf74f5f3584711f17f

**Comment by Sharlikran** [comment]
And an extra added bonus, https://github.com/ESOUIMods/ESO_QuestMap/commit/3da1a3d62c42555d686d86d79de0d548f5308aac.

Japanese courtesy of @fireundubh from the xEdit team!

**Comment by Sharlikran** [comment]
@MikeZeDev @Gimplekin @Necropsi Thank you all for helping. Please submit any remaining `QuestMapScout.lua` files even if you are not finished collecting data for the project.

After you submit your last remaining `QuestMapScout.lua` file delete it and uninstall Quest Map Log and Quest Map Scout.

Then with Minion download [LibQuestInfo](https://www.esoui.com/downloads/info2625-LibQuestInfo.html). It will be doing all the data collection from now on. You will submit new data from LibQuestInfo to [LibQuestInfo:Github/1](https://github.com/ESOUIMods/LibQuestInfo/issues/1).

Thank you again for your help.

**Comment by MikeZeDev** [comment]
[last.zip](https://github.com/ESOUIMods/ESO_QuestMapScout/files/4640027/last.zip)

**Comment by Necropsi** [comment]
No problem at all, thank you for resurecting this addon!!
Here are the files, Vvardenfell is almost complete, should be done today!

I hope im not asking for too much, but maybe in the future, could there be added filters for Main Story Quests, Zone Quests, Repeateble Quests and Guild Quests? Maybe even Prologue Quests? If yes, and if i can help with anything please let me know!

Thanks again for all your hard work!
[Necropsi.zip](https://github.com/ESOUIMods/ESO_QuestMapScout/files/4640366/Necropsi.zip)

**Comment by Sharlikran** [comment]
Once Vvardenfel is completed, that should be uploaded you can provide the file the same way as you have done. I prefer it being on the LibQuestInfo Github. I want to depreciate Quest Map Scout.

As for your request, some that would already work. It's already planned. It just won't be accurate at first.

It will only become more accurate after I release version 2 of LibQuestInfo and I get more user information submitted.
